const items = [
    {
        id: '001',
        image: 'images/1.jpg',
        company: 'Apple',
        item_name: 'Apple Smart-watch',
        original_price: 12000,
        current_price: 9000,
        discount_percentage: 25,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images/2.jpg',
        company: 'deodorant',
        item_name: 'Boss deodorant 150mL',
        original_price: 350,
        current_price: 300,
        discount_percentage: 14.5,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/3.jpg',
        company: ' Realme',
        item_name: 'Realme Airbuds',
        original_price: 2090,
        current_price: 1400,
        discount_percentage: 30,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/4.jpg',
        company: 'Chanel',
        item_name: 'Choco Noir',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/5.jpeg',
        company: 'Apple',
        item_name: 'Iphone 15 pro max',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/6.jpeg',
        company: 'Iphone',
        item_name: 'iphone 15',
        original_price: 146995,
        current_price: 146995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'images/7.jpeg',
        company: 'Nike',
        item_name: 'Air Jordan',
        original_price: 15999,
        current_price: 6399,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/8.jpeg',
        company: 'Royal radiance',
        item_name: 'Black leather Bracelet',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];
